matrix:
  include:
    - os: linux
      dist: trusty
      language: generic
      sudo: false
    - os: osx
      language: swift
      osx_image: xcode10

script:
  - chmod u+x scripts/build-package.sh
  - scripts/build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10