matrix:
  include:
    - language: generic
      os: linux
      dist: trusty
      sudo: false
    - language: swift
      os: osx
      osx_image: xcode10

script:
  - chmod u+x install-swift.sh
  - ./install-swift.sh
  - swift build

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10