jobs:
  include:
    - os: linux
      dist: xenial
      language: generic
    - os: osx
      osx_image: xcode10.1
      language: swift

script:
  - chmod u+x scripts/build-package.sh
  - scripts/build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10